<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/commande.js');?>"></script>

<?php


echo '
<div class="widget" style="border:0px">
<form style="margin:20px">
<div class="section">
		<label> Id <small></small></label>
		<div>
			<input disabled="disabled" id="id" name="id" type="text" class="validate[required] medium id_pack" maxlength="20" value="' . $this->commande->id_commande . '">
		</div>
	</div>
	<div class="section alphaonly">
		<label>Description<small>Un petit mot sur le service</small></label>
		<div>
			<textarea name="description">'.$this->commande->libelle_commande.'</textarea>
		</div>
	</div>
	<div class="section">
		<label>Documents : <small>utiliser cette solution pour generer des documents cette commande</small></label>
		<div>
			<a href="'.$this->url ( array ('id' => $this->commande->id_commande ), 'facture' ).'" class="button blue serif skew facture" data-icon="✔">Facture</a>
		</div>
	</div>
	<div class="section">
		<label>Liste des éléments<small>Veuillez definir le type de votre client</small></label>
		<div>
			<input type="checkbox" id="show_type" name="liste_type" class="liste_type"
				value="1" /><span class="f_help"></span>
		</div>
	</div>
	</form>
</div>

<div class="widget" style="padding:20px ;border:0px">
	
		<div id="projets">';
		
$i = 0;
echo '
<div id="UITab_projets">

<div class="tab_container">

<div id="tab1_projets" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<table class="display data_table2 projet"  id="projets">
<thead>
<tr>

<th align="left">Id</th>
<th>Date debut</th>
<th>Date fin</th>
<th>Status</th>
<th>Paiement</th>
<th>Type de projet</th>
<th>Management</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_projets as $projet ) {
	
	echo '<tr>
	<td  class="id_projet" align ="left">' . $projet ['id_projet'] . '</td>';
	
		echo '<td class="date_debut">' . $projet ['date_debut'] . '</td>
		<td class="date_fin">' . $projet ['date_fin'] . '</td>
		<td class="status">' . $projet ['status'] . '</td>
		<td class="paiement">' . $projet ['paye'] . '</td>';
		$type_projet_string = NULL;
		foreach ($this->list_types_projets as $type_projet){
			if($type_projet['id_type_projet'] == $projet['id_type_projet']){
				$type_projet_string = $type_projet['nom_type_projet'];
			}
		}
		echo '<td>' . $type_projet_string. '</td>';
		echo '
		<td>
		<span class="tip" >
		<a  title="Edit" class="edit_projet" href="';
		echo $this->url ( array ('id' => $projet ['id_projet'] ), 'projetmodify' );
		echo '">
		<img src="images/icon/icon_edit.png" >
		</a>
		</span>
		<span class="tip" >
		<a id="p' . $i . '" class="Delete_projet"  name="Band ring" title="Delete">
		<img src="images/icon/icon_delete.png">
		</a>
		</span>
		</td>
		</tr>';
		$i ++;

}

echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>
		
		
		</div>

	
	<div id="services" style="display:none">
		<?php
$i = 0;
echo '
<div id="UITab_services">

<div class="tab_container">

<div id="tab1_services" class="tab_content" style="display : block">
<div class="load_page">

<form>
<div class="tableName inTab">

<table class="display data_table2 service"  id="services">
<thead>
<tr>

<th align="left">Id</th>
<th>Date debut</th>
<th>Date fin</th>
<th>Status</th>
<th>Paiement</th>
<th>Type de service</th>
<th>Management</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_services as $service ) {
	
	echo '<tr>
	<td  class="id_service" align ="left">' . $service ['id_service'] . '</td>';
	
		echo '<td class="date_debut">' . $service ['date_debut'] . '</td>
		<td class="date_fin">' . $service ['date_fin'] . '</td>
		<td class="status">' . $service ['status'] . '</td>
		<td class="paiement">' . $service ['paye'] . '</td>';
		$type_service_string = NULL;
		foreach ($this->list_types_services as $type_service){
			if($type_service['id_type_service'] == $service['id_type_service']){
				$type_service_string = $type_service['libelle_type_service'];
			}
		}
		echo '<td>' . $type_service_string. '</td>';
		// get the poste name
		echo '
		<td>
		<span class="tip" >
		<a  title="Edit" class="edit_service" href="';
		echo $this->url ( array ('id' => $service ['id_service'] ), 'servicemodify' );
		echo '">
		<img src="images/icon/icon_edit.png" >
		</a>
		</span>
		<span class="tip" >
		<a id="s' . $i . '" class="Delete_service"  name="Band ring" title="Delete">
		<img src="images/icon/icon_delete.png">
		</a>
		</span>
		</td>
		</tr>';
		$i ++;
}

echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>
		
		
		</div>

</div>