

<form action="#">
	<div class="section alphaonly">
		<label> Nom <small>Nom du client</small></label>
		<div>
			<input name="text[]" type="text" class="medium" maxlength="4">
		</div>
	</div>
	<div class="section alphaonly">
		<label> Prenom <small>Prenom complet du client</small></label>
		<div>
			<input name="text[]" type="text" class="medium" maxlength="4">
		</div>
	</div>
	<div class="section ">
		<label>Genre<small></small></label>
		<div>
			<div>
				<input type="radio" name="opinions" id="radio-1" value="1"
					class="ck" /> <label for="radio-1">Homme</label>
			</div>
			<div>
				<input type="radio" name="opinions" id="radio-2" value="1"
					class="ck" checked="checked" /> <label for="radio-2">Femme</label>
			</div>
		</div>
	</div>

	<div class="section ">
		<label> E-mail<small>l'adresse mail du client</small></label>
		<div>
			<input type="text" class="validate[required,custom[email]]  large"
				name="e_required" id="e_required">
		</div>
	</div>
	<div class="section">
		<label> Adresse <small>L'adresse complet du client</small></label>
		<div>
			<input type="text" name="text[]" class=" full" /><span class="f_help">Ex : Adresse du bureau ou de la maison</span>
		</div>
	</div>

	<div class="section numericonly">
		<label> Telephone <small>Numero de Telephone</small></label>
		<div>
			<input name="text" type="text" class="small">
		</div>
	</div>

	<div class="section numericonly">
		<label> Fax <small>Numero de Fax</small></label>
		<div>
			<input name="text" type="text" class="small">
		</div>
	</div>

	<div class="section last">
		<div>
			<a class="uibutton submit_form">Enregistrer</a>
			<a class="uibutton special" title="Reset Form" onclick="ResetForm()">Reprendre</a>
		</div>
	</div>

</form>
