<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/client.js');?>"></script>
	
	<script type="text/javascript">
$(document).ready(function(){
			//check the right gender 'homme' ou 'femme'
			if($('.hidden_gender').attr('value') == 0){
					$('label[for="radio-1"]').addClass('checked');
					$('label[for="radio-2"]').removeClass('checked');

				}else{
					$('label[for="radio-2"]').addClass('checked');
					$('label[for="radio-1"]').removeClass('checked');
					}
});
</script>
	
	<?php 
	echo '
<form id="particulier" class="f_c_p_modify formEl_b">
		<fieldset>
			<legend>
				Particulier <span class="small s_color"></span>
			</legend>
			<div class="section">
		<label> Id <small></small></label>
		<div>
			<input disabled="disabled" id="id" name="id" type="text" class="validate[required] medium id_client" maxlength="20" value="' . $this->client['id_client'] . '">
		</div>
	</div>
				<div class="section alphaonly">
					<label>Nom<small></small></label>
					<div>
						<input id="nom_p" name="nom_p" type="text"
							class="validate[required] medium nom_p" maxlength="20" value="' . $this->client['nom'] . '">
					</div>
				</div>
				<div class="section alphaonly">
					<label> Prénom <small></small></label>
					<div>
						<input id="firstname_p" name="prenom_p" type="text"
							class="medium prenom_p" maxlength="20" value="' . $this->client['prenom'] . '">
					</div>
				</div>

				<div class="section ">
					<label>gender<small>Text custom</small></label>
					<div>
						<div>
							<input type="radio" name="gender_p" id="radio-1" value="0"
								class="ck_p gender_p" /> <label for="radio-1">Homme</label>
						</div>
						<div>
							<input type="radio" name="gender_p" id="radio-2" value="1"
								class="ck_p gender_p" /> <label for="radio-2">Femme</label>
						</div>
					</div>
				</div>
				<div class="section">
					<label> E-mail<small>Text custom</small></label>
					<div>
						<input type="text" id="email_p"
							class="validate[custom[email]]  large email_p"
							name="email_p" id="" value="' . $this->client['email'] . '">
					</div>
				</div>
				<div class="section numericonly">
					<label> Tél <small>Text custom</small></label>
					<div>
						<input id="tel_p" name="tel_p" type="text"
							class="validate[required] small tel_p" maxlength="20" value="' . $this->client['tel'] . '">
					</div>
				</div>
		
		</fieldset>
		<div class="section last">
			<div>
				<a class="button blue back submit_form modify_client_particulier"
					data-icon="⏏">Update</a> <a id="reset_p"
					class="button pink glossy glass">Reset</a>
					<input class="hidden_gender" type="hidden" value="' . ($this->client['gender'] == "Homme" ? "0" : "1") . '">
			</div>
		</div>

</form>';

?>