<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/projet.js');?>"></script>

<?php 

echo  '<form id="add_projet" class="f_p_add">
<div class="section">
	<label>Commande<small>La commande à laquel ce projet appartient</small></label>
	<div>
	<select data-placeholder="Veuillez choisir une commande..."
	class="chzn-select" tabindex="2">
	<option value=""></option>';
foreach($this->list_commandes as $commande){
		echo "<option value=".$commande['id_commande'].">".$commande['id_commande']."</option>";
}
echo '</select><span class="f_help">Veuillez choisir un client</span>
	</div>
	</div>';

echo '
	<div class="section alphaonly">
		<label>Description<small>Un petit mot sur le projet</small></label>
		<div>
			<textarea name="description"></textarea>
		</div>
	</div>
	<div class="section">
     <label>Prix<small>Donner un prix</small></label>
         <div>
             <input type="text" id="sStep" value="1000.00" name="prix" class="prix"/>
           </div>
     </div>
	<div class="section">
		<label>Date debut</label>
		<div>
			<input type="text" id="datepick" class="datepicker date_debut"
				readonly="readonly" name="date_debut" />
		</div>
	</div>

	<div class="section">
		<label>Date fin</label>
		<div>
			<input type="text" id="datepick2" class="datepicker date_fin"
				readonly="readonly" name="date_fin" />
		</div>
	</div>

	<div class="section">
		<label>Status<small>Veuillez definir un status initial pour ce projet</small></label>
		<div>
			<input type="checkbox" id="status" name="status" class="status"
				value="1" /> <span class="f_help"></span>
				<input value="interrompu" type="hidden" id="status_hidden" name="status_hidden" class="status_hidden"
				value="" />
		</div>
	</div>';
	echo '	
	<div class="section">
		<label> Employe <small>Définir la liste des employés qui travaillent dans ce projet</small></label>
		<div>
			<select class="chzn-select" multiple tabindex="4">
				<option value=""></option>';
foreach($this->list_employes as $employe)
{
	echo "<option value=".$employe['nom'].">".$employe['nom']."</option>";
}
					
echo'	</select>
		</div>
	</div>
	
	<div class="section last">
		<div>
			<a class="button green back add_projet">Ajouter</a> 
			<a id="reset" class="button pink glossy glass">Reset</a>
		</div>
	</div>

</form>';
?>
