<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('style.css');?>" />
</head>


<div class="right_content">
	<h2>Bienvenue !</h2>
	<div class="widgets">
							<div class="oneTwo">
								<div class="widget">
								 <div class="header"><span><span class="ico color location"></span>  Services </span></div>
									<div class="content">
                          
						  
						  
						  

									</div>
								 </div>
							</div>
							<div class="oneTwo">
								<div class="widget">
								 <div class="header"><span><span class="ico color stats_lines"></span>Projets en cours</span></div>
									<div class="content">
                          
						  
						  
						  
						  
						  
						  
						  
						  

									</div>
								 </div>
							</div>

	</div>
</div>
</html>