<html>
<head>
<link rel="stylesheet" type="text/css"
	href="<?php echo $this->baseUrl('style.css');?>" />
</head>


<div class="right_content">
	<h2>Bienvenue !</h2>
	<div class="widgets">
		<div class="oneTwo">
			<div class="widget">
				<div class="header">
					<span><span class="ico color location"></span> Services </span>
				</div>
				<div class="content"></div>
			</div>
		</div>
		<div class="oneTwo">
			<div class="widget">
				<div class="header">
					<span><span class="ico color stats_lines"></span>Projets en cours</span>
				</div>
				<div class="content"></div>
			</div>
		</div>

	</div>
	<div class="widgets">
		<div class="oneTwo">
			<div class="widget">
				<div class="header">
					<span><span class="ico gray stats_lines"></span>Site Statistics</span>
				</div>
				<div class="content">
					<br class="clear" />


					<!-- Third / Half column-->
					<div class="widgets">
						<div class="oneThree">
							<div class="shoutcutBox">
								<span class="ico color chat-exclamation"></span> <strong>23</strong>
								<em>Service actifs</em>
							</div>
							<div class="breaks">
								<span></span>
							</div>
							<!-- // breaks -->
							<div class="shoutcutBox">
								<span class="ico color item"></span> <strong>1,538</strong> <em>
									Projets en création</em>
							</div>
							<div class="shoutcutBox">
								<span class="ico color group"></span> <strong>4,452</strong> <em>Total
									Employés</em>
							</div>
							<br />
							<br />
						</div>


					</div>
					<!-- End Third / Half column-->

					<!-- clear fix -->
					<div class="clear"></div>

				</div>
				<!-- End content -->
			</div>
			<!-- End full width -->

		</div>
		<div class="oneTwo">
			<div class="widget">
				<div class="header">
					<span><span class="ico color stats_lines"></span>Alertes</span>
				</div>
				<div class="content">
					<div class="alertMessage SE">3 SERVICE NE SONT PAS ENCORE PAYE</div>
					<div class="alertMessage success SE">FELICITATION 1 PROJET EST FINI</div>
					<div class="alertMessage warning SE">ATTENTION 3 Nom de domaine vont expirer dans 1 mois</div>
				</div>
			</div>
		</div>

	</div>
</div>
</html>