<form action="#">
	<div class="section alphaonly">
		<label> Nom <small></small></label>
		<div>
			<input name="text[]" type="text" class="medium" maxlength="20">
		</div>
	</div>
	<div class="section alphaonly">
		<label> Prénom <small></small></label>
		<div>
			<input name="text[]" type="text" class="medium" maxlength="20">
		</div>
	</div>
	<div class="section ">
		<label>Genre<small>Text custom</small></label>
		<div>
			<div>
				<input type="radio" name="opinions" id="radio-1" value="1"
					class="ck" /> <label for="radio-1">Homme</label>
			</div>
			<div>
				<input type="radio" name="opinions" id="radio-2" value="1"
					class="ck" checked="checked" /> <label for="radio-2">Femme</label>
			</div>
		</div>
	</div>

	<div class="section ">
		<label> E-mail<small>Text custom</small></label>
		<div>
			<input type="text" class="validate[required,custom[email]]  large"
				name="e_required" id="e_required">
		</div>
	</div>
	<div class="section">
		<label> Adresse <small>Text custom</small></label>
		<div>
			<input type="text" name="text[]" class=" full" /><span class="f_help">Text
				custom help</span>
		</div>
	</div>



	<div class="section numericonly">
		<label> Telephone <small>Text custom</small></label>
		<div>
			<input name="text" type="text" class="small">
		</div>
	</div>

	<div class="section">
		<label> Compte d'utilisateur <small>Text custom</small></label>
		<div>
			<input type="text" name="username" id="username"
				class="validate[required,minSize[3],maxSize[20],] medium" /><label>Nom
				d'utilisateur</label> <span class="f_help"> Username login or
				register. <br />Should be between 3 and not more than 20 characters.
			</span>
		</div>
		<div>
			<input type="password" class="validate[required,minSize[3]] medium"
				name="password" id="password" /><label>Mot de passe</label>
		</div>
		<div>
			<input type="password"
				class="validate[required,equals[password]] medium"
				name="passwordCon" id="passwordCon" /><label>Confirmer le mot de
				passe</label> <span class="f_help"> Your password should be at least
				6 characters.</span>
		</div>
	</div>


	<div class="section">
		<label>Poste<small>some text</small></label>
		<div>
			<select data-placeholder="Veuillez choisir un poste..."
				class="chzn-select" tabindex="2">
				<option value=""></option>
				<option value="United States">Employé</option>
				<option value="United Kingdom">Stagiaire</option>
				<option value="Afghanistan">Freelance</option>
			</select>
		</div>
	</div>
	<div class="section">
		<label> Occupation <small>Text custom</small></label>
		<div>
			<select class="chzn-select " multiple tabindex="4">
				<option value=""></option>
				<option value="United States">Programmeur</option>
				<option value="United Kingdom">Designateur</option>
				<option value="United Kingdom">Integrateur</option>
				<option value="United Kingdom">Analyste et modelisateur</option>
			</select>
		</div>
	</div>
	<div class="section last">
		<div>
			<a class="uibutton submit_form">Enregistrer</a>
		</div>
	</div>

</form>
