

<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/employe.js');?>"></script>

<h5 class="test"></h5>

<ul class="uibutton-group">
	<li><a class="uibutton icon add "
		href="<?php echo $this->url(array('controller' => 'employe', 'action' => 'add' ),'default',true);?>">Ajouter</a></li>
	<li class="delete_b"><a class="uibutton special">Supprimer</a></li>
	<li class="selectall"><a class="uibutton confirm">De/Selectionner tous</a></li>
	
</ul>
	
	
<?php
$i = 0;
$poste_name = NULL;
echo '
<div id="UITab">

<div class="tab_container">

<div id="tab1" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<h3 id="test"></h3>
<table class="display data_table2 employe"  id="data_table3">
<thead>
<tr>

<th align="left">Id</th>
<th>Nom</th>
<th>Prenom</th>
<th>Email</th>
<th>Poste</th>
<th>Management</th>
</tr>
</thead>
<tbody>';
foreach ( $this->list_employes as $employe ) {
	echo '<tr>
<td  class="id_employe" align ="left">' . $employe ['id_employe'] . '</td>
<td class="nom">' . $employe ['nom'] . '</td>
<td>' . $employe ['prenom'] . '</td>
<td>' . $employe ['mail'] . '</td>';
//get the poste name
foreach($this->list_postes as $poste){
	if($poste['id_poste'] == $employe ['id_poste'])
	{
		$poste_name = $poste['nom_poste'];
	}
}

echo '
<td>' . $poste_name . '</td>

<td>
	<span class="tip" >
	<a  title="Edit" class="edit" href="';
	echo $this->url(array('id' => $employe ['id_employe']),'employemodify');
	echo '">
	<img src="images/icon/icon_edit.png" >
	</a>
	</span>
	<span class="tip" >
	<a id="' . $i . '" class="Delete"  name="Band ring" title="Delete">
	<img src="images/icon/icon_delete.png">
	</a>
	</span>
</td>
</tr>';
	$i ++;
};
echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>
