
<div>
	<a class="uibutton icon add "
		href="<?php echo $this->url(array('controller' => 'service', 'action' => 'add' ),'default',true);?>">Ajouter</a>
	<a class="uibutton  icon edit  special"
		href="<?php echo $this->url(array('controller' => 'service', 'action' => 'modify' ),'default',true);?>">Modifier</a>
	<a class="uibutton special"
		href="<?php echo $this->url(array('controller' => 'service', 'action' => 'delete' ),'default',true);?>">Supprimer</a>
	<a class="uibutton confirm"
		href="<?php echo $this->url(array('controller' => 'service', 'action' => 'profil' ),'default',true);?>">Plus de details</a>

</div>



<?php
echo '<div class="tableName">
							<h3>Liste des Services</h3>

<table class="display data_table2 dataTable" >
	<thead>
		<tr>
			<th><div class="th_wrapp">ID</div></th>
			<th><div class="th_wrapp">Description</div></th>
			<th><div class="th_wrapp">Type du Service</div></th>
			<th><div class="th_wrapp">Type du Pack</div></th>
			<th><div class="th_wrapp">Status</div></th>
			<th><div class="th_wrapp">Date de Desactivation</div></th>
		</tr>
	</thead>
	<tbody>
		<tr class="odd gradeX">
			<td>0</td>
			<td>Ali</td>
			<td>Safrioui</td>
			<td>Homme</td>
			<td class="center">Bloc C N 3 CITE DAKHLA AGADIR</td>
			<td class="center">0612352499</td>
		</tr>
		<tr class="odd gradeX">
			<td>1</td>
			<td>Majda</td>
			<td>Kadiri</td>
			<td>Femme</td>
			<td class="center">Bloc A N 12 CITE HOUDA AGADIR</td>
			<td class="center">0642518264</td>
		</tr>
		<tr class="odd gradeX">
			<td>0</td>
			<td>Ali</td>
			<td>Safrioui</td>
			<td>Homme</td>
			<td class="center">Bloc C N 3 CITE DAKHLA AGADIR</td>
			<td class="center">0612352499</td>
		</tr>
	</tbody>
</table>
</div>'?>

