<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/occupation.js');?>"></script>

<h5 class="test"></h5>

<ul class="uibutton-group">
	<li><a class="uibutton icon add "
		href="<?php echo $this->url(array('controller' => 'occupation', 'action' => 'add' ),'default',true);?>">Ajouter</a></li>
	
	<li class="delete_b"><a class="uibutton special">Supprimer</a></li>
	<li class="selectall"><a class="uibutton confirm">De/Selectionner tous</a></li>
</ul>
<?php
$i = 0;
echo '
<div id="UITab">

<div class="tab_container">

<div id="tab1" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<h3 id="test"></h3>
<table class="display data_table2 occupation"  id="data_table3">
<thead>
<tr>

<th align="left">Id</th>
<th>Description</th>
<th>Management</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_occupations as $occupation ) {
	echo '<tr>
<td  class="id_occup" align ="left">' . $occupation ['id_occup'] . '</td>
<td class="nom_occup">' . $occupation ['nom_occup'] . '</td>
<td>
<span class="tip" >
<a  title="Edit" class="edit" href="';
echo $this->url(array('id' => $occupation ['id_occup']),'occupationmodify');
echo '">
<img src="images/icon/icon_edit.png" >
</a>
</span>
<span class="tip" >
<a id="' . $i . '" class="Delete"  name="Band ring" title="Delete">
<img src="images/icon/icon_delete.png">
</a>
</span>
</td>
</tr>';
	$i ++;
};
echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>


